language: go

go:
    - "1.8"
    - "1.9"
    - "1.10"
    - "tip"

script:
    - go test -v -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)

addons:
    code_climate:
        repo_token: 42136a24528a7d52e98adbe0d5126c8dadda18158a8559eec3ee4f73a2053436
