language: go

go:
	- 1.2.1
    - 1.3.3
    - 1.4.2
    - 1.5.0
    - tip

script:
    - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)

