language: go

go:
    - 1.3.3
    - 1.4.2
    - 1.5.0
    - tip

before_install:
    - pip install --user codecov
    - go get github.com/onsi/gomega
    - go get github.com/onsi/ginkgo
    - go get code.google.com/p/go.tools/cmd/cover

script:
    - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)

